/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_ratouis;

/**
 *
 * @author LOAN
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        texte_intro = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        tentatives_actuelles = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        tentatives_restantes = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        nb_chiffre_exact = new javax.swing.JLabel();
        nb_chiffre_trop_haut = new javax.swing.JLabel();
        nb_chiffre_trop_bas = new javax.swing.JLabel();
        nb_chiffre_exact_res = new javax.swing.JLabel();
        nb_chiffre_trop_haut_res = new javax.swing.JLabel();
        nb_chiffre_trop_bas_res = new javax.swing.JLabel();

        jButton10.setText("jButton10");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        texte_intro.setText("Trouve le bon code en moins de 5 tentatives");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 17, 333, 24));

        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_0.setText("0");
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 70));

        texte_chiffre_1.setBackground(new java.awt.Color(204, 204, 204));
        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_1.setText("0");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 90));

        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_2.setText("0");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 50));

        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_3.setText("0");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, 90));

        up_chiffre_1.setBackground(new java.awt.Color(204, 204, 204));
        up_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        up_chiffre_1.setText("^");
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        up_chiffre_2.setBackground(new java.awt.Color(204, 204, 204));
        up_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 30));

        up_chiffre_3.setBackground(new java.awt.Color(204, 204, 204));
        up_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 30));

        up_chiffre_4.setBackground(new java.awt.Color(204, 204, 204));
        up_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        up_chiffre_4.setText("^");
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 30));

        down_chiffre_1.setBackground(new java.awt.Color(204, 204, 204));
        down_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        down_chiffre_1.setText("\\/");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        down_chiffre_2.setBackground(new java.awt.Color(204, 204, 204));
        down_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        down_chiffre_2.setText("\\/");
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 30));

        down_chiffre_3.setBackground(new java.awt.Color(204, 204, 204));
        down_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        down_chiffre_3.setText("\\/");
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 70, 30));

        down_chiffre_4.setBackground(new java.awt.Color(204, 204, 204));
        down_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        down_chiffre_4.setText("\\/");
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, 30));

        tentatives_actuelles.setText("Nombre de tentavives : ");
        getContentPane().add(tentatives_actuelles, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, 20));

        bouton_recommencer.setBackground(new java.awt.Color(204, 204, 204));
        bouton_recommencer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bouton_recommencer.setText("Recommencer");
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 160, -1));

        tentatives_restantes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tentatives_restantes.setText("0/5");
        getContentPane().add(tentatives_restantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 60));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setText("Tester");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 90, -1));

        nb_chiffre_exact.setText("Nombre de chiffres exacts :");
        getContentPane().add(nb_chiffre_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        nb_chiffre_trop_haut.setText("Nombre de chiffres trop hauts :");
        getContentPane().add(nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        nb_chiffre_trop_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        nb_chiffre_exact_res.setText("0");
        getContentPane().add(nb_chiffre_exact_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        nb_chiffre_trop_haut_res.setText("0");
        getContentPane().add(nb_chiffre_trop_haut_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        nb_chiffre_trop_bas_res.setText("0");
        getContentPane().add(nb_chiffre_trop_bas_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel nb_chiffre_exact;
    private javax.swing.JLabel nb_chiffre_exact_res;
    private javax.swing.JLabel nb_chiffre_trop_bas;
    private javax.swing.JLabel nb_chiffre_trop_bas_res;
    private javax.swing.JLabel nb_chiffre_trop_haut;
    private javax.swing.JLabel nb_chiffre_trop_haut_res;
    private javax.swing.JLabel tentatives_actuelles;
    private javax.swing.JLabel tentatives_restantes;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
